### ISSUE TITLE
account resources weird behaviour

### ISSUE THREAD

**Issue by dev-dantealighieri** [greymass/eosio-resources#7]
when i check my account resources, used cpu amount is decreasing and i cant understand why? i bought some resources using powerup model, im spending them. after sometime, my used cpu resource amount is decreasing, quite interesting and can't figure it out, could you please provide more information what might cause this or why this is happening?

thanks, dante

```ts
const result = await client.apiClient.v1.chain.get_account(address);
result.cpu_limit.used // this value is decreasing ???
```

**Comment by aaroncox** [comment]
I believe what's happening here is that as more CPU is reserved, it globally impacts everyone ever so slightly. 

I'm not 100% sure though and don't have a definitive answer. Might need to seek clarity elsewhere on this one, perhaps Telegram.

**Comment by dev-dantealighieri** [comment]
sometimes i see my used used and usedall cpu is 15ms, but max is 5ms, how is that possible, and why is that happening? im using powerup model, is this happening because i rent resources couple of times in a day? even though, this is strange behaviour, why is that happening?
