### ISSUE TITLE
cpu resource confusion

### ISSUE THREAD

**Issue by dev-dantealighieri** [greymass/eosio-resources#8]
```ts
used: accountObject.cpu_limit.current_used,
usedAll: accountObject.cpu_limit.used,
```

what is difference of this fields? which one i can use to track my usedcpu amount, and why value of used continuously changing even though im not buying or spending cpu?

**Comment by aaroncox** [comment]
I believe one of them is a snapshot of the amount used, which doesn't update in real time - while the other is one that updates in real time as resources replenish.

It's how the API endpoints return the data, so we just mirror it.
